disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - type_name
  - line_length
  - type_body_length
  - force_cast
  - function_body_length
  - vertical_parameter_alignment
  - file_length
  - todo
  - redundant_string_enum_value
  - function_parameter_count
included:
  - FlagPhoneNumber
excluded:
  - Pods
opt_in_rules:
  - unneeded_parentheses_in_closure_argument
  - array_init
  - file_name
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  # - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - let_var_whitespace
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
    # - vertical_parameter_alignment_on_call
  - yoda_condition